AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB table to test SnapStart
Transform: AWS::Serverless-2016-10-31
Resources:
  # DynamoDB
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
Outputs:
  outTable:
    Value: !GetAtt Table.Arn