AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function with Spring Boot application
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31
Globals:
  Api:
    OpenApiVersion: 3.0.1
  Function:
    Layers:
      - !Sub 'arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:38'
    MemorySize: !Ref pFnMemory
    Timeout: !Ref pFnTimeout
Parameters:
  pApiStage:
    Type: String
  pFnMemory:
    Type: Number
  pFnTimeout:
    Type: Number
  pFnAliasName:
    Type: String
  pSnapStartApplyOn:
    Type: String
  pTableArn:
    Type: String
Resources:
  # APIGW
  Api:
    Type: AWS::Serverless::Api
    Properties:
      AccessLogSetting:
        DestinationArn: !GetAtt ApiLogGroup.Arn
        Format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod","routeKey":"$context.routeKey", "status":"$context.status","protocol":"$context.protocol", "responseLength":"$context.responseLength", "auth.status":"$context.authorizer.status", "auth.error":"$context.authorizer.error", "auth.token":"$context.authorizer.token", "auth.reason":"$context.authorizer.reason", "auth.simple":"$context.authorizer.simple", "auth.pversion":"$context.authorizer.pversion" }'
      MethodSettings:
        - HttpMethod: '*'
          LoggingLevel: INFO
          ResourcePath: '/*'
          MetricsEnabled: true
          DataTraceEnabled: true
      StageName: !Ref pApiStage
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: openapi.yaml
      EndpointConfiguration:
        Type: REGIONAL
  ApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/snapstart-${Api}"
      RetentionInDays: 7
  # Lambda (Core backend using Spring Boot 2)
  FnRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/service-role/'
      Policies:
        - PolicyName: cloudwatch-insights
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: '*'
        - PolicyName: cloudwatch-logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: 'arn:aws:logs:*:*:log-group:*:*'
        - PolicyName: vpc-lattice-logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:ListLogDeliveries
                  - vpc-lattice:CreateAccessLogSubscription
                  - vpc-lattice:GetAccessLogSubscription
                  - vpc-lattice:UpdateAccessLogSubscription
                  - vpc-lattice:DeleteAccessLogSubscription
                  - vpc-lattice:ListAccessLogSubscription
                Resource: '*'
        - PolicyName: dynamodb
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DeleteItem
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                Resource: !Ref pTableArn
  Fn:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java17
      CodeUri: ../target/demo-0.0.1-SNAPSHOT.jar
      Handler: cloud.heeki.DemoHandler::handleRequest
      Role: !GetAtt FnRole.Arn
      AutoPublishAlias: !Ref pFnAliasName
      AutoPublishAliasAllProperties: true
      DeploymentPreference:
        Type: AllAtOnce
      SnapStart:
        ApplyOn: !Ref pSnapStartApplyOn
      Environment:
        Variables:
          TABLE: !Select [1, !Split ["/", !Ref pTableArn]]
  FnLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Fn}"
      RetentionInDays: 7
  FnPerm:
    DependsOn: FnAliaslive
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub '${Fn.Arn}:${pFnAliasName}'
      Principal: apigateway.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*/*/*'
  # Lambda (Alternate backend using Python)
  FnPy:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.11
      CodeUri: ../src/listener
      Handler: fn.handler
      Role: !GetAtt FnRole.Arn
      Layers:
        - !Ref Layer
  FnPyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${FnPy}"
      RetentionInDays: 7
  FnPyPerm:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt FnPy.Arn
      Principal: apigateway.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*/*/*'
  # Layers
  Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.10
        - python3.11
      ContentUri: ../tmp/layer
      LayerName: python3-listener
Outputs:
  outApi:
    Value: !Ref Api
  outApiEndpoint:
    Value: !Sub 'https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${pApiStage}'
  outFn:
    Value: !Ref Fn
  outFnArn:
    Value: !GetAtt Fn.Arn
  outFnPy:
    Value: !Ref FnPy
  outFnPyArn:
    Value: !GetAtt FnPy.Arn
