AWSTemplateFormatVersion: "2010-09-09"
Description: EKS service account for pod permissions
Parameters:
  pOidcProvider:
    Type: String
  pNamespace:
    Type: String
  pServiceAccount:
    Type: String
  pTableArn:
    Type: String
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      # AssumeRolePolicyDocument:
      #   Version: '2012-10-17'
      #   Statement:
      #     - Effect: Allow
      #       Principal:
      #         Federated: !Sub "arn:aws:iam::${AWS::AccountId}:oidc-provider/${pOidcProvider}"
      #       Action:
      #         - sts:AssumeRoleWithWebIdentity
      #       Condition:
      #         StringEquals:
      #           # cannot sub for the key -> https://github.com/aws/amazon-eks-pod-identity-webhook/issues/30
      #           !Sub "${pOidcProvider}:aud": "sts.amazonaws.com"
      #           !Sub "${pOidcProvider}:sub": !Sub "system:serviceaccount:${pNamespace}:${pServiceAccount}"
      AssumeRolePolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Federated": "arn:aws:iam::${AWS::AccountId}:oidc-provider/${pOidcProvider}"
              },
              "Action": "sts:AssumeRoleWithWebIdentity",
              "Condition": {
                "StringEquals": {
                  "${pOidcProvider}:aud": "sts.amazonaws.com",
                  "${pOidcProvider}:sub": "system:serviceaccount:${pNamespace}:${pServiceAccount}"
                }
              }
            }
          ]
        }
      Path: "/"
      Policies:
        - PolicyName: dynamodb
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DeleteItem
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                Resource: !Ref pTableArn
Outputs:
  outRole:
    Value: !Ref Role
  outRoleArn:
    Value: !GetAtt Role.Arn
